/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_memorystorageadapter_free: (a: number, b: number) => void;
export const memorystorageadapter_new: () => number;
export const memorystorageadapter_load: (a: number, b: any) => any;
export const memorystorageadapter_loadRange: (a: number, b: any) => any;
export const memorystorageadapter_save: (a: number, b: any, c: any) => any;
export const memorystorageadapter_remove: (a: number, b: any) => any;
export const memorystorageadapter_listOneLevel: (a: number, b: any) => any;
export const __wbg_beelay_free: (a: number, b: number) => void;
export const beelay_load: (a: any) => any;
export const beelay_peer_id: (a: number) => any;
export const beelay_createContactCard: (a: number) => any;
export const beelay_createDoc: (a: number, b: any) => any;
export const beelay_createGroup: (a: number, b: any) => any;
export const beelay_addMember: (a: number, b: any) => any;
export const beelay_removeMember: (a: number, b: any) => any;
export const beelay_addCommits: (a: number, b: any) => any;
export const beelay_addBundle: (a: number, b: any) => any;
export const beelay_loadDocument: (a: number, b: any) => any;
export const beelay_waitForDocument: (a: number, b: any) => any;
export const beelay_createStream: (a: number, b: any) => [number, number, number];
export const beelay_stop: (a: number) => any;
export const beelay_on: (a: number, b: any, c: any) => [number, number];
export const beelay_off: (a: number, b: any, c: any) => [number, number];
export const beelay_version: (a: number) => [number, number];
export const beelay_waitUntilSynced: (a: number, b: any) => any;
export const beelay_isStopped: (a: number) => number;
export const parseBeelayDocId: (a: any) => [number, number, number];
export const __wbg_memorysigner_free: (a: number, b: number) => void;
export const memorysigner_new: (a: number) => [number, number, number];
export const memorysigner_verifying_key: (a: number) => [number, number];
export const memorysigner_signing_key: (a: number) => [number, number];
export const memorysigner_sign: (a: number, b: number, c: number) => any;
export const __wbg_streamhandle_free: (a: number, b: number) => void;
export const streamhandle_on: (a: number, b: any, c: any) => [number, number];
export const streamhandle_recv: (a: number, b: any) => [number, number];
export const streamhandle_disconnect: (a: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h6f86344c83913053: (a: number, b: number) => void;
export const closure1133_externref_shim: (a: number, b: number, c: any) => void;
export const closure1661_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
