//! Operations for updating prekeys.

pub mod add_key;
pub mod rotate_key;

use self::{add_key::AddKeyOp, rotate_key::RotateKeyOp};
use crate::{principal::identifier::Identifier, util::content_addressed_map::CaMap};
use derive_more::{From, TryInto};
use dupe::Dupe;
use keyhive_crypto::{
    digest::Digest,
    share_key::ShareKey,
    signed::{Signed, VerificationError},
    verifiable::Verifiable,
};
use serde::{Deserialize, Serialize};
use std::{
    collections::{HashMap, HashSet},
    sync::Arc,
};

/// Operations for updating prekeys.
///
/// Note that the number of keys only ever increases.
/// This prevents the case where all keys are removed and the user is unable to be
/// added to a [`Cgka`][crate::cgka::Cgka].
#[derive(Debug, Clone, Dupe, PartialEq, Eq, Hash, Serialize, Deserialize, From, TryInto)]
#[cfg_attr(any(test, feature = "arbitrary"), derive(arbitrary::Arbitrary))]
pub enum KeyOp {
    /// Add a new key.
    Add(Arc<Signed<AddKeyOp>>),

    /// Retire and replace an existing key.
    Rotate(Arc<Signed<RotateKeyOp>>),
}

impl KeyOp {
    pub fn topsort(key_ops: &CaMap<KeyOp>) -> Vec<Arc<KeyOp>> {
        let mut heads: Vec<Arc<KeyOp>> = vec![];
        let mut rotate_key_ops: HashMap<ShareKey, Vec<Arc<KeyOp>>> = HashMap::new();

        for key_op in key_ops.values() {
            match key_op.as_ref() {
                KeyOp::Add(_add) => {
                    heads.push(key_op.dupe());
                }
                KeyOp::Rotate(rot) => {
                    rotate_key_ops
                        .entry(rot.payload.old)
                        .or_default()
                        .push(key_op.dupe());
                }
            }
        }

        // A rotation is a head exactly when the key it consumed is produced by no op in this map,
        // neither an `Add` nor another `Rotate`. That state is routine rather than exceptional: a
        // contact card is generated by rotating a prekey, so whoever receives a rotated card
        // builds an individual from that rotation alone. Seeding only from `Add` ops would
        // serialize such an individual to zero ops, and `reachable_prekey_ops_for_all_agents`
        // would then advertise no prekeys for it — no peer could ever obtain them, and the next
        // grant naming that individual would fail prekey selection. Rotations reached from the op
        // that produced their consumed key are walked below, so seeding here cannot duplicate.
        let produced: HashSet<ShareKey> = key_ops
            .values()
            .map(|op| match op.as_ref() {
                KeyOp::Add(add) => add.payload.share_key,
                KeyOp::Rotate(rot) => rot.payload.new,
            })
            .collect();
        for (old, rotations) in &rotate_key_ops {
            if !produced.contains(old) {
                for op in rotations {
                    heads.push(op.dupe());
                }
            }
        }

        // A rotation-only state can also be *cyclic*: `k1 → k2` together with `k2 → k1` makes every
        // consumed key produced by another op in the map, so the loop above seeds nothing and this
        // function returns zero ops for a state that holds two. That is the same outcome the
        // rotation-only case above exists to prevent — no peer can obtain this individual's
        // prekeys, so the next grant naming it fails prekey selection — and it is reachable once
        // the `Add` that created the consumed key has been pruned. A cycle has no causal entry
        // point, so any of its rotations can start the walk; the `emitted` dedup below terminates
        // it and emits each rotation once. Seeds are ordered by op digest because the map's
        // iteration order is not stable and this output decides what we advertise to peers.
        if heads.is_empty() && !rotate_key_ops.is_empty() {
            let mut seeds: Vec<(Digest<KeyOp>, Arc<KeyOp>)> = rotate_key_ops
                .values()
                .flatten()
                .map(|op| (Digest::hash(op.as_ref()), op.dupe()))
                .collect();
            seeds.sort_by(|(left, _), (right, _)| left.as_slice().cmp(right.as_slice()));
            heads.extend(seeds.into_iter().map(|(_, op)| op));
        }

        let mut topsorted = vec![];
        let mut emitted: HashSet<ShareKey> = HashSet::new();

        while let Some(head) = heads.pop() {
            // A rotation cycle (k1→k2, then k2→k1) reaches an op whose key was already emitted.
            // Cycles are representable, since the map is keyed causally, so following one would
            // never terminate and emitting it twice would duplicate prekeys.
            if !emitted.insert(*head.new_key()) {
                continue;
            }

            if let Some(ops) = rotate_key_ops.get(head.new_key()) {
                for op in ops.iter() {
                    heads.push(op.dupe());
                }
            }

            topsorted.push(head.dupe());
        }

        topsorted
    }

    pub fn new_key(&self) -> &ShareKey {
        match self {
            KeyOp::Add(add) => &add.payload.share_key,
            KeyOp::Rotate(rot) => &rot.payload.new,
        }
    }

    pub fn try_verify(&self) -> Result<(), VerificationError> {
        match self {
            KeyOp::Add(add) => add.try_verify(),
            KeyOp::Rotate(rot) => rot.try_verify(),
        }
    }

    pub fn issuer(&self) -> &ed25519_dalek::VerifyingKey {
        match self {
            KeyOp::Add(add) => &add.issuer,
            KeyOp::Rotate(rot) => &rot.issuer,
        }
    }

    pub fn signature(&self) -> &ed25519_dalek::Signature {
        match self {
            KeyOp::Add(add) => &add.signature,
            KeyOp::Rotate(rot) => &rot.signature,
        }
    }
}

impl Verifiable for KeyOp {
    fn verifying_key(&self) -> ed25519_dalek::VerifyingKey {
        match self {
            KeyOp::Add(add) => add.verifying_key(),
            KeyOp::Rotate(rot) => rot.verifying_key(),
        }
    }
}

/// Reachable prekey ops for all agents, with shared storage.
///
/// Instead of duplicating topsorted key ops across agents, the ops are stored
/// once in `ops` and each agent has an index into that shared map.
#[derive(Debug)]
pub struct AllReachablePrekeyOps {
    /// Topsorted key ops per identifier (agent, group, or doc), computed once.
    pub ops: HashMap<Identifier, Vec<Arc<KeyOp>>>,

    /// For each agent: the set of identifiers whose ops in `ops` are reachable, plus
    /// members it can no longer reach whose keys still help verify the history it is
    /// sent.
    pub index: HashMap<Identifier, HashSet<Identifier>>,
}

impl AllReachablePrekeyOps {
    /// Returns the set of agent identifiers that have reachable ops.
    pub fn agents(&self) -> impl Iterator<Item = &Identifier> {
        self.index.keys()
    }

    /// Returns an iterator over all reachable [`KeyOp`]s for the given agent
    /// (flattened across all source identifiers), or `None` if the agent is not
    /// in the index.
    pub fn ops_for_agent(
        &self,
        agent_id: &Identifier,
    ) -> Option<impl Iterator<Item = &Arc<KeyOp>>> {
        self.index.get(agent_id).map(|ids| {
            ids.iter()
                .filter_map(|id| self.ops.get(id))
                .flat_map(|ops| ops.iter())
        })
    }
}
