name: Rust

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lint-test-audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Build
      run: cargo build --verbose
    - name: Build with Test Utils
      run: cargo build --verbose --features=test_utils
    - name: Check
      run: cargo check --verbose --features=test_utils
    - name: Test on Host
      run: cargo test --verbose --features=test_utils
    - name: Test on Wasm
      run: wasm-pack test --node beehive_wasm
    - name: Test in browsers
      run: wasm-pack build ./beehive_wasm --release --target=web && cd ./beehive_wasm && pnpm i && pnpm exec playwright test
    - name: Clippy
      run: cargo clippy
    - name: Compile benches
      run: cargo bench --features=test_utils --no-run
    - name: Security vulnerability audit
      run: cargo audit
