name: "spellcheck"

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  CLICOLOR: 1

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: crate-ci/typos@v1
